language: php

env:
    -DB=mysql

# only want to build master branch
branches:
    only:
        - master
# installing the code climate test coverage push-thingy via composer
install:
    - composer require codeclimate/php-test-reporter --dev
    - composer update
    - composer install 

before_script:
    - mkdir app/tmp
    - chmod -R 777 app/tmp
    - chmod +x ./codeclimate.sh
    - sh -c "mysql -e 'CREATE DATABASE pollutantDB_test;'"
    - sh -c "mysql -u travis pollutantDB_test < app/Config/Schema/pollutantDB.sql"
    - echo "<?php 
                class DATABASE_CONFIG { 
                    public \$test = array(
                    'datasource' => 'Database/Mysql',
                    'persistent' => false,
                    'host' => '0.0.0.0',
                    'login' => 'travis',
                    'database' => 'pollutantDB_test',
                    'encoding' => 'utf8'); }"
          > app/Config/database.php

script:
    - app/Console/cake test app AllTests --coverage-clover build/logs/clover.xml

after_script:
    ./codeclimate.sh

notifications:
    # no notifications for now.
    email: false;
